FROM quay.io/quarkus/ubi9-quarkus-micro-image:2.0
WORKDIR /work/

# Copy the native executable into the container
COPY --chown=1001:root *-runner /work/application

# Create cache directory and set permissions
RUN mkdir -p /work/cache && chown -R 1001:root /work/cache

EXPOSE 8080
USER 1001

CMD ["./application", "-Dquarkus.http.host=0.0.0.0"]
